"""create core tables

Revision ID: 27cb92c5c256
Revises: 
Create Date: 2025-11-21 18:38:18.466328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27cb92c5c256'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_image_library',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('dimensions', sa.String(length=20), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('upload_batch', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ad_image_author', 'ad_image_library', ['author'], unique=False)
    op.create_index('idx_ad_image_batch', 'ad_image_library', ['upload_batch'], unique=False)
    op.create_table('campaign',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('channels', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('regions', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('launch_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_campaign_creator', 'campaign', ['created_by'], unique=False)
    op.create_table('template',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('html_file_path', sa.Text(), nullable=False),
    sa.Column('max_videos', sa.Integer(), nullable=False),
    sa.Column('static_assets_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('poster_url', sa.Text(), nullable=False),
    sa.Column('view_count', sa.BigInteger(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('idx_video_category', 'video', ['category'], unique=False)
    op.create_index('idx_video_status', 'video', ['status'], unique=False)
    op.create_table('workflow',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_creator', 'workflow', ['created_by'], unique=False)
    op.create_index('idx_workflow_status', 'workflow', ['status'], unique=False)
    op.create_table('campaign_workflow_map',
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('workflow_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'workflow_id')
    )
    op.create_index('idx_cwm_campaign', 'campaign_workflow_map', ['campaign_id'], unique=False)
    op.create_index('idx_cwm_workflow', 'campaign_workflow_map', ['workflow_id'], unique=False)
    op.create_table('landing_page',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.BigInteger(), nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=False),
    sa.Column('selected_video_ids', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('generated_page_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'template_id', name='uq_workflow_template')
    )
    op.create_index('idx_landing_page_template', 'landing_page', ['template_id'], unique=False)
    op.create_index('idx_landing_page_workflow', 'landing_page', ['workflow_id'], unique=False)
    op.create_table('workflow_ad_map',
    sa.Column('workflow_id', sa.BigInteger(), nullable=False),
    sa.Column('ad_image_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ad_image_id'], ['ad_image_library.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workflow_id', 'ad_image_id')
    )
    op.create_index('idx_wam_ad_image', 'workflow_ad_map', ['ad_image_id'], unique=False)
    op.create_index('idx_wam_workflow', 'workflow_ad_map', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_wam_workflow', table_name='workflow_ad_map')
    op.drop_index('idx_wam_ad_image', table_name='workflow_ad_map')
    op.drop_table('workflow_ad_map')
    op.drop_index('idx_landing_page_workflow', table_name='landing_page')
    op.drop_index('idx_landing_page_template', table_name='landing_page')
    op.drop_table('landing_page')
    op.drop_index('idx_cwm_workflow', table_name='campaign_workflow_map')
    op.drop_index('idx_cwm_campaign', table_name='campaign_workflow_map')
    op.drop_table('campaign_workflow_map')
    op.drop_index('idx_workflow_status', table_name='workflow')
    op.drop_index('idx_workflow_creator', table_name='workflow')
    op.drop_table('workflow')
    op.drop_index('idx_video_status', table_name='video')
    op.drop_index('idx_video_category', table_name='video')
    op.drop_table('video')
    op.drop_table('template')
    op.drop_index('idx_campaign_creator', table_name='campaign')
    op.drop_table('campaign')
    op.drop_index('idx_ad_image_batch', table_name='ad_image_library')
    op.drop_index('idx_ad_image_author', table_name='ad_image_library')
    op.drop_table('ad_image_library')
    # ### end Alembic commands ###
